# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' Alternative to readLines that is faster
#' @description
#' This alternative is from \link{https://gist.github.com/hadley/6353939}
#'
#' @param x Integer Vector
#' @return
#' A logical vector, as per \code{duplicated}
#'
#' @export
#' @rdname duplicated
readLinesRcpp <- function(path) {
    .Call('_reproducible_readLinesRcpp', PACKAGE = 'reproducible', path)
}

